name: ramadan_app
description: Ramazan uygulaması - İftar, Sahur, Namaz Saatleri, Kuran Ayetleri

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  adhan: ^2.0.0
  intl: ^0.19.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  android_alarm_manager_plus: ^4.0.1
  audioplayers: ^6.0.0
  permission_handler: ^11.3.0
  flutter_timezone: ^2.1.0
  hijri: ^3.0.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  lottie: ^3.1.0
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/