name: ramadan_app
description: Ramazan uygulaması - İftar, Sahur, Namaz Saatleri, Kuran Ayetleri

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  adhan: ^2.0.0
  intl: ^0.19.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  android_alarm_manager_plus: ^4.0.1
  audioplayers: ^6.0.0
  permission_handler: ^11.3.0
  timezone: ^0.9.4
  hijri: ^3.0.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  flutter_launcher_icons: ^0.14.4
  google_mobile_ads: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png" # İkon dosyanızın yolu
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  
  # İŞTE BEYAZ ÇERÇEVEYİ YOK EDEN AYARLAR:
  adaptive_icon_background: "#11162B" # Görselinizdeki koyu lacivert tonu
  adaptive_icon_foreground: "assets/icon/icon.png"